version: '3.1' 

services:
    service-trap:
        restart: always
        build:
            context: ./        
        expose:
            - 22           
        environment:        
            - SERVICETRAP_HTTP_PORT=22
            - SERVICETRAP_DB_USER=service-trap-user
            - SERVICETRAP_DB_PASSWORD=verrysecurepassword
            - SERVICETRAP_DB_NAME=trapblocklist
            - SERVICETRAP_DB_HOST=supercluster.example.com
            - SERVICETRAP_DB_PORT=3306
            - SERVICETRAP_DB_TABLE=banned
            - SERVICETRAP_DB_COLUMN=ip
            - SERVICETRAP_LISTEN_PORT=22
            - SERVICETRAP_LISTEN_ADDRESS=0.0.0.0
            #Data Category not yet used
            - SERVICETRAP_DATA_CATEGORY=default
            #TCP is the only protocol working. Maybe i'm going to add udp and IPv6 to it later
            - SERVICETRAP_LISTEN_PROTOCOL=tcp
